# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MVVM-C Template' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-C Template
  pod 'RxSwift',    '~> 3.2'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxRealm',    '~> 0.6'
  pod 'Realm',      '2.5'
  pod 'RealmSwift', '2.5'


  target 'MVVM-C TemplateTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

  target 'MVVM-C TemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
        end
    end
end
